'use server';
/**
 * @fileOverview An AI agent that recommends a complete outfit based on user preferences and current weather conditions.
 *
 * - generateOutfitRecommendation - A function that handles the outfit recommendation process.
 * - GenerateOutfitRecommendationInput - The input type for the generateOutfitRecommendation function.
 * - GenerateOutfitRecommendationOutput - The return type for the generateOutfitRecommendation function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const WardrobeItemSchema = z.object({
  id: z.string().describe('Unique identifier for the clothing item.'),
  clothingType: z.string().describe('Type of clothing (e.g., shirt, pants, shoes, jacket, dress, skirt, sweater).'),
  mainColor: z.string().describe('Main color of the clothing item (e.g., red, blue, black, white, grey).'),
  style: z.string().describe('Style of the clothing item (e.g., casual, formal, sporty).'),
});

const GenerateOutfitRecommendationInputSchema = z.object({
  preferredStyle: z.string().describe('The user\u0027s preferred style (e.g., \u0027casual\u0027, \u0027formal\u0027, \u0027sporty\u0027).'),
  temperatureCelsius: z.number().describe('Current temperature in Celsius.'),
  isRaining: z.boolean().describe('True if it is currently raining, false otherwise.'),
  wardrobe: z.array(WardrobeItemSchema).describe('A list of clothing items available in the user\u0027s virtual wardrobe.'),
});
export type GenerateOutfitRecommendationInput = z.infer<typeof GenerateOutfitRecommendationInputSchema>;

const RecommendedOutfitItemSchema = z.object({
  id: z.string().describe('The ID of the recommended clothing item from the wardrobe.'),
  clothingType: z.string().describe('Type of clothing.'),
  mainColor: z.string().describe('Main color of the clothing item.'),
  style: z.string().describe('Style of the clothing item.'),
  reason: z.string().describe('A brief explanation why this item was chosen for the outfit.'),
});

const GenerateOutfitRecommendationOutputSchema = z.object({
  recommendedOutfit: z.array(RecommendedOutfitItemSchema).describe('A list of clothing items forming the recommended outfit.'),
});
export type GenerateOutfitRecommendationOutput = z.infer<typeof GenerateOutfitRecommendationOutputSchema>;

export async function generateOutfitRecommendation(input: GenerateOutfitRecommendationInput): Promise<GenerateOutfitRecommendationOutput> {
  return generateOutfitRecommendationFlow(input);
}

const outfitRecommendationPrompt = ai.definePrompt({
  name: 'outfitRecommendationPrompt',
  input: { schema: GenerateOutfitRecommendationInputSchema },
  output: { schema: GenerateOutfitRecommendationOutputSchema },
  prompt: `You are a professional fashion stylist. Your goal is to recommend a complete and stylish outfit from the user's virtual wardrobe based on their preferences and current weather conditions.

Here are the details:
- User's Preferred Style: "{{{preferredStyle}}}"
- Current Temperature: {{{temperatureCelsius}}} degrees Celsius
- Is it Raining: {{#if isRaining}}Yes{{else}}No{{/if}}

Here is the user's available wardrobe:
{{#each wardrobe}}
- ID: {{{id}}}, Type: {{{clothingType}}}, Color: {{{mainColor}}}, Style: {{{style}}}
{{/each}}

Based on the preferred style, weather conditions, and available clothes, select a cohesive outfit.
Consider the temperature (e.g., warmer clothes for lower temperatures, lighter for higher), rain (e.g., recommend waterproof/suitable items if raining), and overall color compatibility.
Ensure the outfit is complete (e.g., includes a top, a bottom, and shoes, and potentially an outerwear item like a jacket or sweater if the temperature or rain suggests it).
Do not recommend items that are not in the provided wardrobe. For example, if the user asks for a jacket, but there are no jackets in the wardrobe, do not recommend one.
Prioritize matching the preferred style.

Output your recommendation as a JSON object with a single field 'recommendedOutfit', which is an array of clothing items. Each item must include its 'id', 'clothingType', 'mainColor', 'style', and a brief 'reason' for its selection.`,
});

const generateOutfitRecommendationFlow = ai.defineFlow(
  {
    name: 'generateOutfitRecommendationFlow',
    inputSchema: GenerateOutfitRecommendationInputSchema,
    outputSchema: GenerateOutfitRecommendationOutputSchema,
  },
  async (input) => {
    try {
      const { output } = await outfitRecommendationPrompt(input);
      if (!output) {
        throw new Error('No recommendation was generated by the AI.');
      }
      return output;
    } catch (error) {
      console.error('Error in generateOutfitRecommendationFlow:', error);
      throw error;
    }
  }
);
